version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: omni_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: omni_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: omni_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: omni_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    command: server /data --console-address ":9001"

  postgresql-client:
    image: dpage/pgadmin4
    container_name: omni_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "3412:80"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: omni_redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"  # RedisInsight web UI

volumes:
  postgres_data:
  minio_data:
